jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

name: workflow

'on':
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    # generated randomly
    - cron: '18 11 * * FRI'
